//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterWeb.Client.MonsterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonsterServiceReference.IMonsterService")]
    public interface IMonsterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetGender", ReplyAction="http://tempuri.org/IMonsterService/GetGenderResponse")]
        MonsterApp.DataClient.Models.GenderDAO[] GetGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetGender", ReplyAction="http://tempuri.org/IMonsterService/GetGenderResponse")]
        System.Threading.Tasks.Task<MonsterApp.DataClient.Models.GenderDAO[]> GetGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetMonsterType", ReplyAction="http://tempuri.org/IMonsterService/GetMonsterTypeResponse")]
        MonsterApp.DataClient.Models.MonsterTypeDAO[] GetMonsterType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetMonsterType", ReplyAction="http://tempuri.org/IMonsterService/GetMonsterTypeResponse")]
        System.Threading.Tasks.Task<MonsterApp.DataClient.Models.MonsterTypeDAO[]> GetMonsterTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetTitles", ReplyAction="http://tempuri.org/IMonsterService/GetTitlesResponse")]
        MonsterApp.DataClient.Models.TitleDAO[] GetTitles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetTitles", ReplyAction="http://tempuri.org/IMonsterService/GetTitlesResponse")]
        System.Threading.Tasks.Task<MonsterApp.DataClient.Models.TitleDAO[]> GetTitlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertMonster", ReplyAction="http://tempuri.org/IMonsterService/InsertMonsterResponse")]
        bool InsertMonster(MonsterApp.DataClient.Models.MonsterDAO monster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertMonster", ReplyAction="http://tempuri.org/IMonsterService/InsertMonsterResponse")]
        System.Threading.Tasks.Task<bool> InsertMonsterAsync(MonsterApp.DataClient.Models.MonsterDAO monster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertGender", ReplyAction="http://tempuri.org/IMonsterService/InsertGenderResponse")]
        bool InsertGender(MonsterApp.DataClient.Models.GenderDAO gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertGender", ReplyAction="http://tempuri.org/IMonsterService/InsertGenderResponse")]
        System.Threading.Tasks.Task<bool> InsertGenderAsync(MonsterApp.DataClient.Models.GenderDAO gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertMonsterType", ReplyAction="http://tempuri.org/IMonsterService/InsertMonsterTypeResponse")]
        bool InsertMonsterType(MonsterApp.DataClient.Models.MonsterTypeDAO mtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertMonsterType", ReplyAction="http://tempuri.org/IMonsterService/InsertMonsterTypeResponse")]
        System.Threading.Tasks.Task<bool> InsertMonsterTypeAsync(MonsterApp.DataClient.Models.MonsterTypeDAO mtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertTitle", ReplyAction="http://tempuri.org/IMonsterService/InsertTitleResponse")]
        bool InsertTitle(MonsterApp.DataClient.Models.TitleDAO title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/InsertTitle", ReplyAction="http://tempuri.org/IMonsterService/InsertTitleResponse")]
        System.Threading.Tasks.Task<bool> InsertTitleAsync(MonsterApp.DataClient.Models.TitleDAO title);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonsterServiceChannel : MonsterWeb.Client.MonsterServiceReference.IMonsterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonsterServiceClient : System.ServiceModel.ClientBase<MonsterWeb.Client.MonsterServiceReference.IMonsterService>, MonsterWeb.Client.MonsterServiceReference.IMonsterService {
        
        public MonsterServiceClient() {
        }
        
        public MonsterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonsterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonsterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonsterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MonsterApp.DataClient.Models.GenderDAO[] GetGender() {
            return base.Channel.GetGender();
        }
        
        public System.Threading.Tasks.Task<MonsterApp.DataClient.Models.GenderDAO[]> GetGenderAsync() {
            return base.Channel.GetGenderAsync();
        }
        
        public MonsterApp.DataClient.Models.MonsterTypeDAO[] GetMonsterType() {
            return base.Channel.GetMonsterType();
        }
        
        public System.Threading.Tasks.Task<MonsterApp.DataClient.Models.MonsterTypeDAO[]> GetMonsterTypeAsync() {
            return base.Channel.GetMonsterTypeAsync();
        }
        
        public MonsterApp.DataClient.Models.TitleDAO[] GetTitles() {
            return base.Channel.GetTitles();
        }
        
        public System.Threading.Tasks.Task<MonsterApp.DataClient.Models.TitleDAO[]> GetTitlesAsync() {
            return base.Channel.GetTitlesAsync();
        }
        
        public bool InsertMonster(MonsterApp.DataClient.Models.MonsterDAO monster) {
            return base.Channel.InsertMonster(monster);
        }
        
        public System.Threading.Tasks.Task<bool> InsertMonsterAsync(MonsterApp.DataClient.Models.MonsterDAO monster) {
            return base.Channel.InsertMonsterAsync(monster);
        }
        
        public bool InsertGender(MonsterApp.DataClient.Models.GenderDAO gender) {
            return base.Channel.InsertGender(gender);
        }
        
        public System.Threading.Tasks.Task<bool> InsertGenderAsync(MonsterApp.DataClient.Models.GenderDAO gender) {
            return base.Channel.InsertGenderAsync(gender);
        }
        
        public bool InsertMonsterType(MonsterApp.DataClient.Models.MonsterTypeDAO mtype) {
            return base.Channel.InsertMonsterType(mtype);
        }
        
        public System.Threading.Tasks.Task<bool> InsertMonsterTypeAsync(MonsterApp.DataClient.Models.MonsterTypeDAO mtype) {
            return base.Channel.InsertMonsterTypeAsync(mtype);
        }
        
        public bool InsertTitle(MonsterApp.DataClient.Models.TitleDAO title) {
            return base.Channel.InsertTitle(title);
        }
        
        public System.Threading.Tasks.Task<bool> InsertTitleAsync(MonsterApp.DataClient.Models.TitleDAO title) {
            return base.Channel.InsertTitleAsync(title);
        }
    }
}
